turtle_patch(action14, action15,
    [run(yellow_playfield,
         [penup, set_pos(14,8), setcolor(yellow),
          pendown, fill_rect(40,42)]),

     hide(green_status_block),

     run(green_fortress,
         [penup, setcolor(green),
          set_pos(19,5), pendown, fill_rect(35,10),
          penup, set_pos(9,10), pendown, fill_rect(15,15),
          penup, set_pos(29,15), pendown, fill_rect(10,10),
          penup, set_pos(44,15), pendown, fill_rect(10,5),
          penup, set_pos(49,20), pendown, fill_rect(10,10),
          penup, set_pos(14,25), pendown, fill_rect(5,13),
          penup, set_pos(34,25), pendown, fill_rect(10,10),
          penup, set_pos(49,30), pendown, fill_rect(5,10),
          penup, set_pos(29,35), pendown, fill_rect(10,10),
          penup, set_pos(12,38), pendown, fill_rect(9,9),
          penup, set_pos(44,40), pendown, fill_rect(15,15),
          penup, set_pos(39,50), pendown, fill_rect(5,5)]),

     run(upper_chamber_interior,
         [penup, set_pos(13,39), setcolor(light_gray),
          pendown, fill_rect(7,7)]),

     run(upper_burgundy_glyph,
         [penup, setcolor(burgundy),
          set_pos(15,41), pendown, fill_rect(3,1),
          penup, set_pos(17,42), pendown, fill_rect(1,2),
          penup, set_pos(15,43), pendown, set_cell]),

     run(bottom_center_gate,
         [penup, set_pos(29,40), setcolor(light_gray),
          pendown, fill_rect(5,2),
          penup, set_pos(29,42), setcolor(burgundy),
          pendown, fill_rect(5,3)]),

     run(blue_black_player,
         [penup, setcolor(blue),
          set_pos(50,47), pendown, set_cell,
          penup, set_pos(51,48), pendown, set_cell,
          penup, set_pos(51,46), setcolor(black),
          pendown, fill_rect(2,2)]),

     run(upper_left_green_target,
         [penup, set_pos(15,16), setcolor(dark_gray),
          pendown, fill_rect(3,3),
          penup, set_pos(16,17), setcolor(green),
          pendown, set_cell]),

     run(lower_right_green_target,
         [penup, set_pos(40,51), setcolor(dark_gray),
          pendown, fill_rect(3,3),
          penup, set_pos(41,52), setcolor(green),
          pendown, set_cell]),

     run(bottom_status_track,
         [penup, set_pos(13,61), setcolor(dark_gray),
          pendown, fill_rect(42,2)])
    ]).
