object_correspondence(parent,current,base_glyph,translation(5,0)).
object_correspondence(parent,current,central_hole,identity).
object_correspondence(parent,current,green_structure,identity).
object_correspondence(parent,current,hud_panel,identity).
object_correspondence(parent,current,left_boundary_bar,identity).
object_correspondence(parent,current,player_cursor,identity).
object_correspondence(parent,current,status_marker,right_extension(1)).
object_correspondence(parent,current,status_pips,identity).
object_correspondence(parent,current,status_track,identity).
object_correspondence(parent,current,top_glyph,identity).

similarity(parent,current,base_glyph,1.0).
similarity(parent,current,central_hole,1.0).
similarity(parent,current,green_structure,1.0).
similarity(parent,current,hud_panel,1.0).
similarity(parent,current,left_boundary_bar,1.0).
similarity(parent,current,player_cursor,1.0).
similarity(parent,current,status_marker,1.0).
similarity(parent,current,status_pips,1.0).
similarity(parent,current,status_track,1.0).
similarity(parent,current,top_glyph,1.0).
