observed_rule(action1_moves_base_glyph_up,five_rows).
observed_rule(action1_advances_status_marker,one_column).

hypothetical_rule(base_glyph_motion,toward_player_cursor,action1).
hypothetical_rule(status_track_progress,one_column_per_action,action1).

evidence(action1_moves_base_glyph_up,parent_bbox(19,40,5,5),current_bbox(19,35,5,5)).
evidence(action1_moves_base_glyph_up,shape_preserved,true).
evidence(action1_advances_status_marker,parent_width(5),current_width(6)).
evidence(base_glyph_motion,current_relative_position,below_player_cursor).
evidence(status_track_progress,new_green_cells,rectangle(18,61,1,2)).

supported_by(action1_moves_base_glyph_up,base_glyph_translation_evidence).
supported_by(action1_advances_status_marker,status_marker_extension_evidence).
supported_by(base_glyph_motion,reduced_vertical_distance_to_player_cursor).
supported_by(status_track_progress,single_rightward_extension).

contradicted_by(action1_moves_base_glyph_up,none).
contradicted_by(action1_advances_status_marker,none).
contradicted_by(base_glyph_motion,insufficient_multiple_step_evidence).
contradicted_by(status_track_progress,insufficient_multiple_action_evidence).
