parent_state(previous).
current_state(current).
action_between(previous,current,'ACTION3').
changed_region(previous,current,53,61,53,62).
cell_color_change(previous,current,53,61,gray,green).
cell_color_change(previous,current,53,62,gray,green).
object_change(status_marker,extended_right,1).
object_bbox_change(status_marker,rect(13,61,52,62),rect(13,61,53,62)).
object_change(status_track,gray_segment_shortened_left,1).
object_part_bbox_change(status_track,gray,rect(53,61,54,62),rect(54,61,54,62)).
unchanged_object(green_structure).
unchanged_object(central_hole).
unchanged_object(player_cursor).
unchanged_object(hud_panel).
unchanged_object(status_pips).
unchanged_object(top_glyph).
unchanged_object(base_glyph).
unchanged_object(left_boundary_bar).
